mysql - readme fix
GoogleCloudPlatform/mysql-docker pull request #74
Opened 2021-09-10 10:34 UTC by EugeneKorolevich

2021-09-13 13:26 UTC, ovk6 requested changes
Move README to root directory (but preserving root README contents)

2021-09-13 13:26 UTC, ovk6 commented on 5/README.md
> +[Official Image marketplace Page](https://console.cloud.google.com/marketplace/details/google/mysql5).
marketplace -> Marketplace

2021-09-13 13:26 UTC, ovk6 commented on 5/README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/container-images)
Marketplace

2021-09-13 13:26 UTC, ovk6 commented on 5/README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/marketplace-container)
Marketplace

2021-09-13 13:26 UTC, ovk6 commented on 8/README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/container-images)
Marketplace

2021-09-13 13:26 UTC, ovk6 commented on 8/README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/marketplace-container)
Marketplace

2021-09-14 09:33 UTC, EugeneKorolevich commented on 5/README.md
> +[Official Image marketplace Page](https://console.cloud.google.com/marketplace/details/google/mysql5).
done

2021-09-14 09:33 UTC, EugeneKorolevich commented on 5/README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/marketplace-container)
done

2021-09-14 09:33 UTC, EugeneKorolevich commented on 8/README.md
> +Consult [marketplace container documentation](https://cloud.google.com/marketplace/docs/marketplace-container)
done

2021-09-21 09:27 UTC, ovk6 approved these changes

2021-09-27 08:03 UTC, merged